FROM node:20-alpine AS base
RUN corepack enable
WORKDIR /app

FROM base AS deps
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_SSU_GROUP_URL_1
ARG NEXT_PUBLIC_SSU_GROUP_URL_2
ARG NEXT_PUBLIC_SSU_GROUP_URL_3
ARG NEXT_PUBLIC_SSU_GROUP_URL_4
ARG NEXT_PUBLIC_SSU_GROUP_URL_5
ARG NEXT_PUBLIC_COMMUNITY_ADMIN_WHATSAPP_URL
ARG NEXT_PUBLIC_SHOW_MONTHLY_HOTEL_PRICE
ARG DATABASE_URL
ENV NEXT_PUBLIC_SSU_GROUP_URL_1=$NEXT_PUBLIC_SSU_GROUP_URL_1 \
    NEXT_PUBLIC_SSU_GROUP_URL_2=$NEXT_PUBLIC_SSU_GROUP_URL_2 \
    NEXT_PUBLIC_SSU_GROUP_URL_3=$NEXT_PUBLIC_SSU_GROUP_URL_3 \
    NEXT_PUBLIC_SSU_GROUP_URL_4=$NEXT_PUBLIC_SSU_GROUP_URL_4 \
    NEXT_PUBLIC_SSU_GROUP_URL_5=$NEXT_PUBLIC_SSU_GROUP_URL_5 \
    NEXT_PUBLIC_COMMUNITY_ADMIN_WHATSAPP_URL=$NEXT_PUBLIC_COMMUNITY_ADMIN_WHATSAPP_URL \
    NEXT_PUBLIC_SHOW_MONTHLY_HOTEL_PRICE=$NEXT_PUBLIC_SHOW_MONTHLY_HOTEL_PRICE \
    DATABASE_URL=$DATABASE_URL \
    NEXT_TELEMETRY_DISABLED=1

RUN pnpm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 PORT=3000

RUN addgroup -g 1001 -S nodejs && adduser -u 1001 -S nextjs -G nodejs

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
